site_name: Irezia - Wiki
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: light mode (puke)
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg