site_name: Irezia - Wiki
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - header.autohide
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
      baselevel: 2
      separator: "_"
      slugify: !!python/name:pymdownx.slugs.uslugify
plugins:
  - git-revision-date-localized
  - search

nav:
  - Home: index.md
  - 'Jobs':
      Mineur: Jobs/Mineur.md
      Pecheur: Jobs/Pecheur.md
      Agriculteur: Jobs/Agriculteur.md
      Bûcheron: jobs/Bucheron.md
      Pêcheur: jobs/Pecheur.md
  - Collections: collections.md
  - Donjons: donjons.md
  - Quêtes: quetes.md
  - Villes: villes.md
copyright: Copyright Irezia 2020 - 2021