site_name: Irezia - Wiki
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.instant

    - navigation.expand
    - navigation.top
    - header.autohide
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - toc:
      permalink: true
  - pymdownx.critic:
      mode: view
  - pymdownx.keys
  - pymdownx.progressbar
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - git-revision-date-localized
  - search
nav:
  - Home: index.md
  - 'Jobs':
      Mineur: Jobs/Mineur.md
      Agriculteur: Jobs/Agriculteur.md
      Bûcheron: Jobs/Bucheron.md
      Pêcheur: Jobs/Pecheur.md
      Chasseur: Jobs/Chasseur.md
  - 'Skills':
      Mining: Skills/Mineur.md
      Farming: Skills/Farming.md
      Combat: Skills/Combat.md
      Foraging: Skills/Foraging.md
      Enchanting: Skills/Enchanting.md
      Alchemy: Skills/Alchemy.md
      Fishing: Skills/Fishing.md
  - Collections: collections.md
  - Donjons: donjons.md
  - Quêtes: quetes.md
  - Villes: villes.md
copyright: Copyright Irezia 2020 - 2021